// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           int64     `json:"id"`
	Owner        string    `json:"owner"`
	AvailBalance int64     `json:"avail_balance"`
	Currency     string    `json:"currency"`
	CreatedAt    time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64        `json:"id"`
	AccountID int64        `json:"account_id"`
	Amount    int64        `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	TransactionID int64         `json:"transaction_id"`
	FromAccID     int64         `json:"from_acc_id"`
	ToAccID       int64         `json:"to_acc_id"`
	Amount        sql.NullInt64 `json:"amount"`
	CreatedAt     sql.NullTime  `json:"created_at"`
}
